export const c = {
  esc:     "\x1b[0m",
  black:     "\x1b[30m",
  red:       "\x1b[31m",
  green:     "\x1b[32m",
  yellow:    "\x1b[33m",
  blue:      "\x1b[34m",
  magenta:   "\x1b[35m",
  cyan:      "\x1b[36m",
  white:     "\x1b[37m",
  blackbg:   "\x1b[40m",
  redbg:     "\x1b[41m",
  greenbg:   "\x1b[42m",
  yellowbg:  "\x1b[43m",
  bluebg:    "\x1b[44m",
  magentabg: "\x1b[45m",
  cyanbg:    "\x1b[46m",
  whitebg:   "\x1b[47m",
  bold:      "\x1b[1m",
  dim:       "\x1b[2m",
  italic:    "\x1b[3m",
  underline: "\x1b[4m",
  rgb: (r: number, g: number, b: number) => `\x1b[38;2;${r};${g};${b}m`,
  rgbbg: (r: number, g: number, b: number) => `\x1b[48;2;${r};${g};${b}m`,
}
